### ISSUE TITLE
Bookmarklet Loader

### ISSUE THREAD

**Issue by pixelfelt** [pixelfelt/pixelfelt-wordpress-theme#3]
- [x] Remove composor (we'll do this with JS instead)
- [x] Create a bookmarklet that loads a manifest.json from CDN that functions similarly to a Chrome Extension manifest for the purposes of loading scripts
- [x] Load required scripts
- [x] Get this working generically
- [x] Get this working for Sketchfab

## Subtasks
- [x] Create an npm account
- [x] Add manifest.json to `pixelfelt-sites` repo
